movie/urls.py
from django.urls import path, reverse_lazy
from .views import Public, Homepage, DetailsMovie, Search, EditProfile, CreateAccount
from django.contrib.auth import views as auth_views

app_name = 'movie'

urlpatterns = [
    # url -  view
    path('', Public.as_view(), name='public'),
    path('movies/', Homepage.as_view(), name='homepage'),
    path('movies/<int:pk>', DetailsMovie.as_view(), name='detailsMovie'),
    path('search/', Search.as_view(), name='search'),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name='logout'),
    path('editProfile/<int:pk>', EditProfile.as_view(), name='editProfile'),
    path('createAccount/', CreateAccount.as_view(), name='createAccount'),
    path('changePassword/', auth_views.PasswordChangeView.as_view(template_name='editProfile.html',
                                                                 success_url = reverse_lazy('movie:homepage')), name='changePassword')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('movie.urls', namespace='movie'))
] 

# Adding the url of the static files
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# Adding the url of media files (user)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

LIST_CATEGORIES = (
    ("ACTION" , "Action"), 
    ("COMEDY", "Comedy"),
    ("DRAMA", "Drama"),
    ("ROMANCE", "Romance"),
    ("DOCUMENTARY", "Documentary"),
    ("SUSPENSE", "Suspense"),
    ("HORROR", "Horror"),
    ("SCIENCE_FICTION", "Science Fiction")
)


class Movie(models.Model):
    title = models.CharField(max_length=100)
    filmCover = models.ImageField(upload_to="covers", default="covers/default_cover.jpg")
    image = models.ImageField(upload_to="images_movies")
    description = models.TextField(max_length=1000)
    category = models.CharField(max_length=20, choices=LIST_CATEGORIES)
    views = models.IntegerField(default=0)
    date = models.DateTimeField()
    
    # String representation 
    def __str__(self):
        return self.title
    
    
class Trailer(models.Model):
    movie = models.ForeignKey("Movie", related_name="trailers", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    url = models.URLField()
    
    # String representation 
    def __str__(self):
        return self.movie.title + " - " + self.title


class User(AbstractUser):
    seen_movies = models.ManyToManyField("Movie")
    

    
    

movie/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms


class FormPublic(forms.Form):
    email = forms.EmailField(label=False)
    

class CreateAccountForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        

movie/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from .models import Movie, Trailer, User
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CreateAccountForm, FormPublic

class Public(FormView):
    template_name = 'public.html'
    form_class = FormPublic
    
    #  Adding the views
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('movie:homepage')
        else:
            return super(Public, self).get(request, *args, **kwargs) # Go to url
    
    # Method access 
    def get_success_url(self):
        email = self.request.POST.get("email")
        user_find = User.objects.filter(email=email)
        if user_find:
            return reverse('movie:login')
        else:
            return reverse('movie:createAccount')
    
    
class Homepage(LoginRequiredMixin, ListView):
    template_name = 'homepage.html'
    model = Movie
    # object_list


class DetailsMovie(LoginRequiredMixin, DetailView):
    template_name = 'detailMovie.html'
    model = Movie
    # object

    #  Adding the views
    def get(self, request, *args, **kwargs):
        movie = self.get_object()
        movie.views += 1
        movie.save()
        user = request.user
        user.seen_movies.add(movie)
        return super(DetailsMovie, self).get(request, *args, **kwargs) # Go to url
    
    # Related movies
    def get_context_data(self, **kwargs):
        context = super(DetailsMovie, self).get_context_data(**kwargs)
        relatedMovies = self.model.objects.filter(Q(category=self.get_object().category) & ~Q(title=self.get_object().title))
        context['relatedMovies'] = relatedMovies
        return context


class Search(LoginRequiredMixin, ListView):
    template_name = 'search.html'
    model = Movie
    
    def get_queryset(self):
        search_term = self.request.GET.get('query')
        if search_term:
            object_list = self.model.objects.filter(Q(title__icontains=search_term) | Q(category__icontains=search_term))
            return object_list
        else:
            return None        


class EditProfile(LoginRequiredMixin, UpdateView):
    template_name = 'editProfile.html'
    model = User
    fields = ['first_name', 'last_name', 'email']
    
    def get_success_url(self):
        return reverse('movie:homepage')
    
    
    
class CreateAccount(FormView):
    template_name = 'createAccount.html'
    form_class = CreateAccountForm
    
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('movie:login')
    

movie/templates/createAccount.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<!-- Title -->
{% block title %}
Create Account
{% endblock %}

<!-- Head -->
{% block head %}
<style>
    header {
        background-size: cover;
        background-position: center;
        height: 100vh;
    }

    ul li, #hint_id_username {
        color: #b7aab0;
        font-size: 12px;
        list-style: none;
    }
</style>
{% endblock %}

<!-- Body -->
{% block content %}
<header class="opacity-50 position-relative"
    style="background-image: url('{% static 'images/background_homepage.jpg' %}');">
</header>

<div
class="bg-black py-4 px-5 position-absolute top-50 start-50 translate-middle d-flex flex-column align-items-center gap-2 text-center text-white">
    <h1 class="fs-3">Create Account</h1>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-danger my-0">Create account</button>
    </form>
</div>
{% endblock %}

movie/templates/detailMovie.html
{% extends 'base.html' %}
{% load static %}

<!-- Title -->
{% block title %}
{{ object.title }}
{% endblock %}

<!-- Head -->
{% block head %}
<link rel="stylesheet" href="{% static 'css/moviesSection.css' %}">
{% endblock %}
<!-- Body -->
{% block content %}

<main class="min-vh-100 w-100 d-flex flex-column text-white">

    <!-- Header -->
    <section id="ctnImage" class="d-flex flex-column justify-content-end opacity-50"
        style="background-image: url('{{ object.image.url }}');">
    </section>

    <section id="infoTitle" class="d-flex flex-column">
        <h1 class="fs-1 fw-bold"> {{ object }}</h1>
        <p> {{ object.description|slice:":150" }}...</p>
        <div>
            <a href=" {{ object.trailers.first.url }}">
                <button class="btn btn-light">
                    <ion-icon name="play"></ion-icon>
                    <span>Play</span>
                </button>
            </a>
        </div>
    </section>

    <!-- More info  -->
    <section id="info" class="container-fluid p-5 w-90 d-flex flex-column justify-content-center gap-2">
        <h4>Description</h4>
        <p class="fw-lighter">{{ object.description }}</p>

        <h4>Trailers</h4>
        {% for trailer in object.trailers.all %}
        <a href="{{trailer.url}}" class="fw-lighter text-white text-decoration-none">
            <p>{{ trailer.title }}</p>
        </a>
        {% endfor %}

        <h4>Views: <p class="fw-lighter" style="display: inline;" >{{ object.views }}</p></h4>
    </section>

    <!-- Related movies -->
    <section class="container-fluid p-5 pt-0 w-90 d-flex flex-column justify-content-center gap-2">
        <h4 style="font-size: 17px;">Related movies</h4>

        <div class="d-flex gap-5">
            {% for movie in relatedMovies %}
            <div id="ctnCover" >
                <a href="{% url 'movie:detailsMovie' movie.id %}">
                    <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}" alt="Images of related movies">
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}

movie/templates/editProfile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<!-- Title -->
{% block title %}
Edit Profile
{% endblock %}

<!-- Head -->
{% block head %}
<style>
    ul li, #hint_id_username {
        color: #b7aab0;
        font-size: 12px;
        list-style: none;
    }
    ul {
        margin-top: 10px;
    }
</style>
{% endblock %}

<!-- Body -->
{% block content %}

<main class="min-vh-100 w-90 d-flex flex-column text-white m-5 p-5">
    <p class="fw-lighter">Hello, {{ user.username }}</p>
    <h1>Edit profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-danger my-0">Edit</button>
    </form>
    <a href="{% url 'movie:changePassword' %}" class="fw-light text-decoration-none mt-4">Change password</a>
</main>


{% endblock %}

movie/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

<!-- Title -->
{% block title %}
Homepage
{% endblock %}

<!-- Head -->
{% block head %}
<style>
    $itemGrow: 1.2;
    $duration: 250ms;

    html {
        scroll-behavior: smooth;
    }

    body {
        margin: 0;
        background-color: #000;
    }

    h1 {
        font-family: Arial;
        color: red;
        text-align: center;
    }

    .wrapper {
        display: grid;
        grid-template-columns: repeat(3, 100%);
        overflow: hidden;
        scroll-behavior: smooth;

        section {
            width: 100%;
            position: relative;
            display: grid;
            grid-template-columns: repeat(5, auto);
            margin: 20px 0;

            .item {
                padding: 0 2px;
                transition: $duration all;

                &:hover {
                    margin: 0 40px;
                    transform: scale(1.2);
                }
            }

            a {
                position: absolute;
                color: #fff;
                text-decoration: none;
                font-size: 6em;
                background: rgb(0, 0, 0);
                width: 80px;
                padding: 20px;
                text-align: center;
                z-index: 1;

                &:nth-of-type(1) {
                    top: 0;
                    bottom: 0;
                    left: 0;
                    background: linear-gradient(-90deg,
                            rgba(0, 0, 0, 0) 0%,
                            rgba(0, 0, 0, 1) 100%);
                }

                &:nth-of-type(2) {
                    top: 0;
                    bottom: 0;
                    right: 0;
                    background: linear-gradient(90deg,
                            rgba(0, 0, 0, 0) 0%,
                            rgba(0, 0, 0, 1) 100%);
                }
            }
        }
    }

    // Remove the arrow for Mobile
    @media only screen and (max-width: 600px) {
        a.arrow__btn {
            display: none;
        }
    }
</style>
<link rel="stylesheet" href="{% static 'css/moviesSection.css' %}">
{% endblock %}

<!-- Body -->
{% block content %}

<main class="min-vh-100 w-100 d-flex flex-column text-white">

    <!-- Header -->
    <section id="ctnImage" class="d-flex flex-column justify-content-end opacity-50 mb-5"
        style="background-image: url('{{ highlight_movie.image.url }}');">
    </section>

    <section id="infoTitle" class="d-flex flex-column">
        <h1 class="fs-1 fw-bold"> {{ object }}</h1>
        <p> {{ highlight_movie.description|slice:":150" }}...</p>
        <div>
            <a href=" {{ highlight_movie.trailers.first.url }}">
                <button class="btn btn-light">
                    <ion-icon name="play"></ion-icon>
                    <span>Play</span>
                </button>
            </a>
        </div>
    </section>

    <!-- Carrousel recent movies -->
    <section class="container-fluid p-5 pt-0 w-90 d-flex flex-column justify-content-center gap-2 mb-5">
        <h4 style="font-size: 17px;" class="mb-5">The most recent movies &#127916;</h4>
        <div class="wrapper">
            <!-- Section 1 - recent movies  -->
            <section id="newSection1" class="d-flex align-items-center justify-content-center gap-5">
                <a href="#newSection1" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">‹</a>
                {% for movie in recent_movies %}
                {% if forloop.counter < 5 %} <div class="item">
                    <a href="{% url 'movie:detailsMovie' movie.id %}">
                        <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}"
                            alt="Images of movies recently added">
                    </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#newSection2" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">›</a>
    </section>
    <!-- Section 2 - recent movies  -->
    {% if recent_movies|length > 4 %}
    <section id="newSection2" class="d-flex align-items-center justify-content-center gap-5">
        <a href="#newSection1" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">‹</a>
        {% for movie in recent_movies %}
        {% if forloop.counter > 5 %}
        <div class="item">
            <a href="{% url 'movie:detailsMovie' movie.id %}">
                <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}"
                    alt="Images of movies recently added">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#newSection2" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">›</a>
    </section>
    {% endif %}
    </div>
    </section>

    <!-- Carrousel hot movies -->
    <section class="container-fluid p-5 pt-0 w-90 d-flex flex-column justify-content-center gap-2 mb-5">
        <h4 style="font-size: 17px;" class="mb-5">What is hot &#128293;</h4>
        <div class="wrapper">
            <!-- Section 1 - hot movies  -->
            <section id="hotSection1" class="d-flex align-items-center justify-content-center gap-5">
                <a href="#hotSection1" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">‹</a>
                {% for movie in hot_movies %}
                {% if forloop.counter < 5 %} <div class="item">
                    <a href="{% url 'movie:detailsMovie' movie.id %}">
                        <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}"
                            alt="Images of the most watched movies">
                    </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#hotSection2" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">›</a>
    </section>
    <!-- Section 2 - hot movies  -->
    {% if hot_movies|length > 4 %}
    <section id="hotSection2" class="d-flex align-items-center justify-content-center gap-5">
        <a href="#hotSection1" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">‹</a>
        {% for movie in hot_movies %}
        {% if forloop.counter > 5 %}
        <div class="item">
            <a href="{% url 'movie:detailsMovie' movie.id %}">
                <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}"
                    alt="Images of the most watched movies">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#hotSection2" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">›</a>
    </section>
    {% endif %}
    </div>
    </section>

     <!-- Carrousel seen movies -->
     <section class="container-fluid p-5 pt-0 w-90 d-flex flex-column justify-content-center gap-2 mb-5">
        <h4 style="font-size: 17px;" class="mb-5">Seen movies &#128064;</h4>
        <div class="wrapper">
            <!-- Section 1 - seen movies  -->
            <section id="seenSection1" class="d-flex align-items-center justify-content-center gap-5">
                <a href="#seenSection1" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">‹</a>
                {% for movie in request.user.seen_movies.all %}
                {% if forloop.counter < 5 %} <div class="item">
                    <a href="{% url 'movie:detailsMovie' movie.id %}">
                        <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}"
                            alt="Images of movies recently added">
                    </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#seenSection2" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">›</a>
    </section>
    <!-- Section 2 - seen movies  -->
    {% if request.user.seen_movies.all|length > 4 %}
    <section id="seenSection2" class="d-flex align-items-center justify-content-center gap-5">
        <a href="#seenSection1" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">‹</a>
        {% for movie in request.user.seen_movies.all %}
        {% if forloop.counter > 5 %}
        <div class="item">
            <a href="{% url 'movie:detailsMovie' movie.id %}">
                <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}"
                    alt="Images of movies recently added">
            </a>
        </div>
        {% endif %}
        {% endfor %}
        <a href="#seenSection2" class="arrow__btn" style="text-decoration: none; color: white; font-size: 30px;">›</a>
    </section>
    {% endif %}
    </div>
    </section>



</main>
{% endblock %}

movie/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

<!-- Title -->
{% block title %}
Login
{% endblock %}

<!-- Head -->
{% block head %}
<style>
    header {
        background-size: cover;
        background-position: center;
        height: 100vh;
    }
</style>
{% endblock %}

<!-- Body -->
{% block content %}
<header class="opacity-50 position-relative"
    style="background-image: url('{% static 'images/background_homepage.jpg' %}');">
</header>

<div
class="bg-black p-5 position-absolute top-50 start-50 translate-middle d-flex flex-column align-items-center gap-2 text-center text-white">
    <h1 class="fs-3">Log in to continue</h1>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}

        <button type="submit" class="btn btn-danger my-0">Login</button>
    </form>

    <p class="my-0 mt-4 fw-light" style="font-size: 14px;">Don't have an account yet?</p>
    <a href="{% url 'movie:createAccount' %}" class="my-0 text-white text-decoration-none fw-medium">
        Click here to create an account
    </a>
</div>


{% endblock %}

movie/templates/logout.html
{% extends 'base.html' %}
{% load static %}

<!-- Title -->
{% block title %}
Logout
{% endblock %}

<!-- Head -->
{% block head %}
<style>
    header {
        background-size: cover;
        background-position: center;
        height: 100vh;
    }
</style>
{% endblock %}

<!-- Body -->
{% block content %}
<header class="opacity-25 position-relative"
    style="background-image: url('{% static 'images/background_homepage.jpg' %}');">
</header>

<div
class="w-100 position-absolute top-50 start-50 translate-middle d-flex flex-column align-items-center gap-2 text-center text-white">
    <h1 class="fs-3">Logout successfully completed</h1>

    <a href="{% url 'movie:public' %}">
        <button type="button" class="btn btn-danger mt-3">Main page</button>
    </a>
</div>

{% endblock %}

movie/templates/public.html
{% extends 'base.html' %}
{% load static %}



<!-- Title -->
{% block title %}
Movieflix
{% endblock %}

<!-- Head -->
{% block head %}
<style>
    #id_email{
        padding: 0px 10px;
        border-radius: 7px;
        margin-right: 10px;
        border: none;
    }
</style>
<link rel="stylesheet" href="{% static 'css/public.css' %}">
{% endblock %}

<!-- Body -->
{% block content %}

<!-- Header -->
<header class="opacity-50 position-relative"
    style="background-image: url('{% static 'images/background_homepage.jpg' %}');">

</header>
<div
    class="w-100
    position-absolute top-50 start-50 translate-middle d-flex flex-column align-items-center gap-2 text-center">
    <h1 class="fs-1 text-white">The best movies you find here!</h1>
    <h4 class="fs-5 text-white">To begin watching, please enter your email below</h4>
    <div class="d-flex mt-2 gap-2">
        <form method="post" class="d-flex">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-danger py-2">Access</button>
        </form>
        
    </div>
</div>

<!-- Section 1 -->
<section class="container-fluid">
    <div class="row p-5 gap-5">
        <div class="col d-flex flex-column align-items-center justify-content-center text-center gap-2">
            <h4 class="fs-4 text-white">
                Enjoy on your TV.
            </h4>
            <h5 class="fw-lighter text-white">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class="col col-sm-12 col-md-6 d-flex justify-content-center">
            <img id="imgTv" src="{% static 'images/tv_homepage.png' %}" alt="TV">
        </div>
    </div>
</section>

<!-- Section 2 -->
<section class="container-fluid">
    <div class="row p-5 gap-5">
        <div class="col col-sm-12 col-md-6 d-flex justify-content-center">
            <img id="imgMobile" src="{% static 'images/mobile_homepage.jpg' %}" alt="Mobile">
        </div>
        <div class="col d-flex flex-column align-items-center justify-content-center text-center gap-2">
            <h4 class="fs-4 text-white">
                Download your shows to watch offline.
            </h4>
            <h5 class="fw-lighter text-white">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>
    </div>
</section>

<!-- Section 3 -->
<section class="container-fluid">
    <div class="row p-5 gap-5">
        <div class="col d-flex flex-column align-items-center justify-content-center text-center gap-2">
            <h4 class="fs-4 text-white">
                Create profiles for kids.
            </h4>
            <h5 class="fw-lighter text-white">
                Send kids on adventures with their favorite characters in a space made just for them.
            </h5>
        </div>
        <div class="col col-sm-12 col-md-6 d-flex justify-content-center">
            <img id="imgKids" src="{% static 'images/kids_homepage.png' %}" alt="Kids">
        </div>
    </div>
</section>

<!-- Footer -->
<footer class="p-2">
    <ul class="d-flex justify-content-center align-items-center m-0 gap-4" style="list-style: none;">
        <li> Made with Django</li>
        <li>&copy; 2023</li>
    </ul>
</footer>

{% endblock %}

movie/templates/search.html
{% extends 'base.html' %}
{% load static %}

<!-- Title -->
{% block title %}
Search results &#128269;
{% endblock %}


<!-- Body -->
{% block content %}

<main class="min-vh-100 w-90 d-flex flex-column text-white m-5 p-5">

    <section class="container-fluid w-90 d-flex flex-column gap-2 p-2">

        <h4 style="font-size: 17px;">Search results  &#128269;</h4>

        <div class="d-flex flex-wrap justify-content-around gap-5">
            {% for movie in object_list %}
            <div id="ctnCover">
                <a href="{% url 'movie:detailsMovie' movie.id %}">
                    <img style="height: 250px; width: 180px;" src=" {{movie.filmCover.url }}"
                        alt="Images of related movies">
                </a>
            </div>
            {% endfor %}
        </div>
    </section>
</main>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">

    {% block head %}
    {% endblock %}

</head>

<body class="bg-black text-gray-100 font-primary">

    <!-- Navbar -->
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

    <!-- JS Navbar  -->
    <script>
        const nav = document.querySelector('nav')
        document.addEventListener("scroll", e => {
            if (scrollY > 100) {
                if (scrollY > window.innerHeight) {
                    nav.classList.add('d-none')
                } else {
                    nav.classList.add('bg-black')
                    nav.classList.remove('d-none')
                }
            } else {
                nav.classList.remove('bg-black')
                nav.classList.remove('d-none')
            }
        })
    </script>

    <!-- JS Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>

    <!-- Ionic Icons -->
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

</body>

</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg fixed-top">
    <div class="container-fluid">
        <!-- Logo -->
        <a class="navbar-brand d-none d-lg-block" href="/">
            <img src="{% static 'images/Movieflix.png'%}" style="width: 150px;" alt="Logo">
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="flex gap-3 collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <!-- Input -->
            {% if user.is_authenticated %}
            <form class="d-flex" role="search" method="get" action="{% url 'movie:search' %}">
                <input class="form-control mb-1" type="search" placeholder="Search by title or category"
                    aria-label="Search" name="query" style="width: 231px;">
                <input type="submit" value="" style="display: none;">
            </form>

            <!-- Edit profile and Logout-->
            <a href="{% url 'movie:editProfile' user.id %}">
                <button type="button" class="btn btn-danger mb-1">Edit profile</button>
            </a>

            <a href="{% url 'movie:logout' %}">
                <button type="button" class="btn btn-danger mb-1">Logout</button>
            </a>
            {% else %}

            <!-- Login -->
            <a href="{% url 'movie:createAccount' %}">
                <button type="button" class="btn btn-danger mb-1">Create account</button>
            </a>

            <a href="{% url 'movie:login' %}">
                <button type="button" class="btn btn-danger mb-1">Login</button>
            </a>
            {% endif %}

        </div>
    </div>
</nav>